name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: Analyze on SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache SonarCloud dependencies
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonarcloud-${{ hashFiles('**/sonar-project.properties') }}
          restore-keys: |
            ${{ runner.os }}-sonarcloud-

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          # No necesitas sonar-token aquí. La acción usa el token configurado en los secretos de GitHub
          projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
          organization: your-sonarcloud-organization
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
